/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form.ThuThu;

import Code.DataBaseAccess;
import Code.HamXuLyBang;
import Code.Sender;
import javax.swing.JOptionPane;

/**
 *
 * @author n18dc
 */
public class PnQlyDocGiaQuaHan extends javax.swing.JPanel {

    /**
     * Creates new form QlyDocGiaQuaHam
     */
    DataBaseAccess dbAccess;
    HamXuLyBang xlyBang;
    public PnQlyDocGiaQuaHan() {
        initComponents();
        dbAccess=new DataBaseAccess();
        xlyBang=new HamXuLyBang();
        loadDGQH();
    }
    
    public void loadDGQH(){
        String sql="SELECT DG.maDocGia, DG.tenDG, DG.SDT, DG.email,DG.diaChi FROM DocGia  DG, (SELECT * FROM PhieuMuon WHERE  trangThai=0) PM, CT_PhieuMuon CTPM WHERE DG.maDocGia=PM.maDocGia AND PM.maPhieuMuon=CTPM.maPhieuMuon AND DATEDIFF(day, CTPM.ngayTra, GETDATE())>0;";
        xlyBang.loadDuLieuVaoBang(jTable_DSDG, sql);
    }
    public void loadCtMuon(String maDG){
        String sql="SELECT S.maISBN, S.tenSach, CTPM.soLuong,S.giaBia,CTPM.ngayTra\n" +
                    "FROM (SELECT * FROM DocGia WHERE maDocGia='"+maDG+"')  DG, \n" +
                    "	(SELECT * FROM PhieuMuon WHERE  trangThai=0) PM, CT_PhieuMuon CTPM,\n" +
                    "	Sach S\n" +
                    "WHERE DG.maDocGia=PM.maDocGia AND PM.maPhieuMuon=CTPM.maPhieuMuon AND DATEDIFF(day, CTPM.ngayTra, GETDATE())>0 AND S.maISBN=CTPM.maSach;";
        xlyBang.loadDuLieuVaoBang(jTable_DSSach, sql);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DSDG = new javax.swing.JTable();
        btnGui = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMaDG = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenDG = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_DSSach = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ĐỘC GIẢ MƯỢN QUÁ HẠN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Danh sách Độc giả:");

        jTable_DSDG.setAutoCreateRowSorter(true);
        jTable_DSDG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Tên độc giả", "SĐT", "Email", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DSDG.setRowHeight(25);
        jTable_DSDG.setRowMargin(3);
        jTable_DSDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DSDGMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_DSDG);

        btnGui.setBackground(new java.awt.Color(51, 51, 255));
        btnGui.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mã độc giả:");

        txtMaDG.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMaDG.setText("Đắt nhân tâm");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tên độc giả:");

        txtTenDG.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTenDG.setText("Lù Vĩnh Trường");

        jTable_DSSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Giá tiền", "Hạn trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DSSach.setRowHeight(25);
        jTable_DSSach.setRowMargin(3);
        jTable_DSSach.setRowSelectionAllowed(false);
        jScrollPane3.setViewportView(jTable_DSSach);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Chi tiêt mượn:");

        txtNoiDung.setColumns(20);
        txtNoiDung.setLineWrap(true);
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nội dung:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SĐT:");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtSDT.setText("Lù Vĩnh Trường");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(523, 523, 523)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGui, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(508, 508, 508))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtMaDG)
                    .addComponent(jLabel12)
                    .addComponent(txtTenDG))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtSDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGui, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        // TODO add your handling code here:
        try {
            Sender sender=new Sender();
            sender.sendSms(txtSDT.getText(), txtNoiDung.getText());
            JOptionPane.showMessageDialog(this, "Gửi tin nhắn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gửi tin nhắn thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnGuiActionPerformed

    private void jTable_DSDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DSDGMouseClicked
        // TODO add your handling code here:
        //if(jTable_DSSach.getSelectionModel().isSelectionEmpty()){return;}
        int rowSelect=jTable_DSDG.getSelectedRow();
        loadCtMuon((String) jTable_DSDG.getValueAt(rowSelect, 0));
        
        txtMaDG.setText((String) jTable_DSDG.getValueAt(rowSelect, 0));
        txtTenDG.setText((String) jTable_DSDG.getValueAt(rowSelect, 1));
        txtSDT.setText((String) jTable_DSDG.getValueAt(rowSelect, 2));
        HamXuLyBang xlyBang=new HamXuLyBang();
        String chiTietMuon="";
        for(int i=0;i<jTable_DSSach.getRowCount();i++){
            chiTietMuon+=" - "+xlyBang.getRow(jTable_DSSach, i, 1)+"(số lượng: "+xlyBang.getRow(jTable_DSSach, i, 2)+", hạn trả: "+xlyBang.getRow(jTable_DSSach, i, 4)+")\n";
        }
        String defaultMes="Xin chào "+txtTenDG.getText()+", hiện tại hệ thống của THƯ VIỆN 10Đ đang ghi nhận độc giả mượn sách quá hạn, chi tiết gồm:\n"+chiTietMuon;
        txtNoiDung.setText(defaultMes);
    }//GEN-LAST:event_jTable_DSDGMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_DSDG;
    private javax.swing.JTable jTable_DSSach;
    private javax.swing.JLabel txtMaDG;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtTenDG;
    // End of variables declaration//GEN-END:variables
}
