/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form.ThuThu;

import Code.DataBaseAccess;
import Code.HamXuLyBang;
import Code.Sender;
import javax.swing.JOptionPane;

/**
 *
 * @author n18dc
 */
public class PnQlyDocGiaQuaHan extends javax.swing.JPanel {

    /**
     * Creates new form QlyDocGiaQuaHam
     */
    DataBaseAccess dbAccess;
    HamXuLyBang xlyBang;
    public PnQlyDocGiaQuaHan() {
        initComponents();
        dbAccess=new DataBaseAccess();
        xlyBang=new HamXuLyBang();
        loadDGQH();
    }
    
    public void loadDGQH(){
        String sql="SELECT DG.maDocGia, DG.tenDG, DG.SDT, DG.email,DG.diaChi FROM DocGia  DG, (SELECT * FROM PhieuMuon WHERE  trangThai=0) PM, CT_PhieuMuon CTPM WHERE DG.maDocGia=PM.maDocGia AND PM.maPhieuMuon=CTPM.maPhieuMuon AND DATEDIFF(day, CTPM.ngayTra, GETDATE())>0;";
        xlyBang.loadDuLieuVaoBang(jTable_DSDG, sql);
    }
    public void loadCtMuon(String maDG){
        String sql="SELECT S.maISBN, S.tenSach, CTPM.soLuong,S.giaBia,CTPM.ngayTra\n" +
                    "FROM (SELECT * FROM DocGia WHERE maDocGia='"+maDG+"')  DG, \n" +
                    "	(SELECT * FROM PhieuMuon WHERE  trangThai=0) PM, CT_PhieuMuon CTPM,\n" +
                    "	Sach S\n" +
                    "WHERE DG.maDocGia=PM.maDocGia AND PM.maPhieuMuon=CTPM.maPhieuMuon AND DATEDIFF(day, CTPM.ngayTra, GETDATE())>0 AND S.maISBN=CTPM.maSach;";
        xlyBang.loadDuLieuVaoBang(jTable_DSSach, sql);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DSDG = new javax.swing.JTable();
        btnGui = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMaDG = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenDG = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_DSSach = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ĐỘC GIẢ MƯỢN QUÁ HẠN");
        add(jLabel1);
        jLabel1.setBounds(445, 33, 232, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Danh sách Độc giả:");
        add(jLabel5);
        jLabel5.setBounds(12, 81, 131, 17);

        jTable_DSDG.setAutoCreateRowSorter(true);
        jTable_DSDG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Tên độc giả", "SĐT", "Email", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DSDG.setRowHeight(25);
        jTable_DSDG.setRowMargin(3);
        jTable_DSDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DSDGMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_DSDG);

        add(jScrollPane2);
        jScrollPane2.setBounds(22, 111, 606, 152);

        btnGui.setBackground(new java.awt.Color(51, 51, 255));
        btnGui.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });
        add(btnGui);
        btnGui.setBounds(548, 591, 115, 47);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mã độc giả:");
        add(jLabel8);
        jLabel8.setBounds(309, 307, 78, 17);

        txtMaDG.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMaDG.setText("Đắt nhân tâm");
        add(txtMaDG);
        txtMaDG.setBounds(391, 307, 170, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tên độc giả:");
        add(jLabel12);
        jLabel12.setBounds(568, 307, 84, 17);

        txtTenDG.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTenDG.setText("Lù Vĩnh Trường");
        add(txtTenDG);
        txtTenDG.setBounds(658, 307, 170, 19);

        jTable_DSSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Giá tiền", "Hạn trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DSSach.setRowHeight(25);
        jTable_DSSach.setRowMargin(3);
        jTable_DSSach.setRowSelectionAllowed(false);
        jScrollPane3.setViewportView(jTable_DSSach);

        add(jScrollPane3);
        jScrollPane3.setBounds(666, 111, 493, 152);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Chi tiêt mượn:");
        add(jLabel7);
        jLabel7.setBounds(666, 87, 99, 17);

        txtNoiDung.setColumns(20);
        txtNoiDung.setLineWrap(true);
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        add(jScrollPane1);
        jScrollPane1.setBounds(262, 411, 716, 167);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nội dung:");
        add(jLabel9);
        jLabel9.setBounds(240, 387, 68, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SĐT:");
        add(jLabel13);
        jLabel13.setBounds(309, 344, 34, 17);

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtSDT.setText("Lù Vĩnh Trường");
        add(txtSDT);
        txtSDT.setBounds(349, 344, 170, 19);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        // TODO add your handling code here:
        if(jTable_DSDG.getSelectionModel().isSelectionEmpty()){// kiểm tra người dùng đã click chọn dữ liệu trong bảng chưa
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả cần gửi tin nhắn trong bảng");
            return;
        }

        try {
            Sender sender=new Sender();
            sender.sendSms(txtSDT.getText(), txtNoiDung.getText());
            JOptionPane.showMessageDialog(this, "Gửi tin nhắn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gửi tin nhắn thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnGuiActionPerformed

    private void jTable_DSDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DSDGMouseClicked
        // TODO add your handling code here:
        //if(jTable_DSSach.getSelectionModel().isSelectionEmpty()){return;}
        int rowSelect=jTable_DSDG.getSelectedRow();
        loadCtMuon((String) jTable_DSDG.getValueAt(rowSelect, 0));
        
        txtMaDG.setText((String) jTable_DSDG.getValueAt(rowSelect, 0));
        txtTenDG.setText((String) jTable_DSDG.getValueAt(rowSelect, 1));
        txtSDT.setText((String) jTable_DSDG.getValueAt(rowSelect, 2));
        HamXuLyBang xlyBang=new HamXuLyBang();
        String chiTietMuon="";
        for(int i=0;i<jTable_DSSach.getRowCount();i++){
            chiTietMuon+=" - "+xlyBang.getRow(jTable_DSSach, i, 1)+"(số lượng: "+xlyBang.getRow(jTable_DSSach, i, 2)+", hạn trả: "+xlyBang.getRow(jTable_DSSach, i, 4)+")\n";
        }
        String defaultMes="Xin chào "+txtTenDG.getText()+", hiện tại hệ thống của THƯ VIỆN 10Đ đang ghi nhận độc giả mượn sách quá hạn, chi tiết gồm:\n"+chiTietMuon;
        txtNoiDung.setText(defaultMes);
    }//GEN-LAST:event_jTable_DSDGMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_DSDG;
    private javax.swing.JTable jTable_DSSach;
    private javax.swing.JLabel txtMaDG;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtTenDG;
    // End of variables declaration//GEN-END:variables
}
